routes/web.php
Route::get('/about','AboutController@about')->name('about');

// Rutas del foro
Route::get('/foro','Foro\ForoController@index')->name('foroIndex');
Route::get('/foro/categoria/view/{id?}','Foro\CategoriaController@index')->name('foroCatIndex');
Route::get('/foro/categoria/posts/{id?}/{page_id?}','Foro\CategoriaController@catPosts')->name('foroCatPosts'); //ajax
Route::get('/foro/categoria/list','Foro\CategoriaController@catList')->name('foroCatList'); //ajax
Route::get('/foro/cat/details','Foro\CategoriaController@details')->name('foroCatDetails'); //ajax
Route::post('/foro/cat/add','Foro\CategoriaController@add')->name('foroCatAdd'); //ajax
Route::put('/foro/cat/edit','Foro\CategoriaController@edit')->name('foroCatEdit'); //ajax
Route::delete('/foro/cat/delete','Foro\CategoriaController@delete')->name('foroCatDelete'); //ajax
Route::get('/foro/favorites', 'Foro\FavoriteController@index')->name('foroFavIndex');
Route::get('/foro/myfavorites', 'Foro\FavoriteController@userFavorites')->name('foroUserFavPost');
Route::get('/foro/myposts', 'Foro\PostController@postsUser')->name('foroPostsUser');
Route::get('/foro/post/view/{id?}','Foro\PostController@index')->name('foroPostIndex');
Route::post('/foro/post/add','Foro\PostController@add')->name('foroPostAdd'); //ajax
Route::get('/foro/post/viewDetail/{id?}','Foro\PostController@viewDetail')->name('foroPostViewDetail'); //ajax
Route::get('/foro/post/details','Foro\PostController@details')->name('foroPostDetails'); //ajax
Route::put('/foro/post/edit','Foro\PostController@edit')->name('foroPostEdit'); //ajax
Route::delete('/foro/post/delete','Foro\PostController@delete')->name('foroPostDelete'); //ajax
Route::get('/foro/post/cmtlist/{id?}','Foro\PostController@cmtList')->name('foroPostCmtList'); //ajax
Route::get('/foro/post/like', 'Foro\PostController@togglePostLike')->name('foroPostLike');//ajax
Route::post('/foro/post/addfav' , 'Foro\FavoriteController@postAddFav')->name('foroPostAddFav');//ajax
Route::post('/foro/cmt/add','Foro\CommentController@add')->name('foroCmtAdd'); //ajax
Route::get('/foro/cmt/details','Foro\CommentController@details')->name('foroCmtDetails'); //ajax
Route::put('/foro/cmt/edit','Foro\CommentController@edit')->name('foroCmtEdit'); //ajax
Route::get('/foro/cmt/like', 'Foro\CommentController@toggleCmtLike')->name('foroCmtLike'); //ajax
Route::delete('/foro/cmt/delete/{id?}', 'Foro\CommentController@delete')->name('foroCmtDelete'); //ajax


// Rutas del testimonios
Route::get('testimonios/{id?}', 'TestimonioController@get_testimonios')->name('testimonios');
// Route::get('testimoniosPublico/{numero?}','PagesController@testimoniosP')->name('testimoniosP');
// Route::get('testimoniosPsicologo/{numero?}','PagesController@testimoniosPsi')->name('testimoniosPsi');
//rutas crud
Route::post('/testimonios/guardar', 'TestimonioController@store');
Route::post('/testimonios/actualizar', 'TestimonioController@update');
//rutas aceptar/rechazar testimonio
Route::post('/testimonios/aceptar', 'TestimonioController@aceptarTesti');
Route::post('/testimonios/rechazar', 'TestimonioController@rechazarTesti');

//Rutas reservas
Route::post('/profile/create', 'CitaController@store')->name('reserva.create');
Route::get('/llamarmodalidad', 'CitaController@modalidadall');
Route::get('/llamarIsapre', 'CitaController@isapres');
Route::get('/llamarServicios', 'CitaController@llamarServicio');
Route::get('/llamarUsuario', 'CitaController@User');
Route::get('/llamarPrecio', 'CitaController@Precio');
Route::get('/llamarHora', 'CitaController@horaNoDisponible');
Route::post('/reagendarCita', 'CitaController@update')->name('reagendar');

//Whatsapp
Route::get('/waping/send', 'WapingController@create');
Route::get('/cita-pendiente/{id}', 'CitaController@analizar');
Route::get('/rechazar/{id}', 'CitaController@rechazo');
Route::get('/confirmar-rechazo/{id}/{estado}', 'CitaController@confirmarRechazo');



Route::get('/mail/send', 'MailController@send');
Route::get('/email/confirmation/{id}', 'MailController@send')->name('confirmacion.email');
Route::get('/Sms', 'SmsController@create');
//Route::get('/Smsnew', 'SmsController@sendsmsnew')->name('enviosms');
Route::get('/vistaemail', 'WapingController@email');


//Rutas Chat
Route::get('chat', 'ChatController@index')->name('modal.chat');
Route::get('/message/{id}','ChatController@getMessage')->name('message');
Route::post('message', 'ChatController@sendMessage');
Route::get('/chat/download/{file}', 'ChatController@downloadFile');
Route::get('/chat/showfile/{filename}', 'ChatController@showFile');
Route::get('/chat/chatform', 'ChatController@index');
Route::get('/chat/read/{id}', 'ChatController@getReadMessages');

// Ruta vista Dashboard
Route::view('/dashboard', 'layouts.dashboard')->name('dashboard');
Route::view('/dashboard/servicios', 'servicios.dashboardServicios')->name('dashboardServicios');
Route::post('/dashboard/update', 'DashboardController@update')->name('dashboardUpdate');
/* Route::view('dashboard/paciente','dashboard.paciente'); */
Route::get('/dashboard/profile/{id}','DashboardController@getProfile');
Route::post('/img/update','DashboardController@postProfileImage')->name('imgUpdate');
Route::post('/updatePassword','DashboardController@updatePassword');
//Route::view('/dashboard', 'layouts.dashboard')->name('dashboard');
//Route::view('/dashboard/servicios', 'servicios.dashboardServicios')->name('dashboardServicios');




// Rutas servicios
Route::resource('servicio', 'ServicioController');
Route::post('/servicio/insertar', 'ServicioController@insertarServicio')->name('rutaFormS');
Route::post('/servicio/eliminar', 'ServicioController@eliminarServicio')->name('rutaFormEliminar');
Route::delete('/servicio/{id}', 'ServicioController@destroy');
Route::get('serviciosall', 'ServicioController@servicioall');


// Inicio Rutas Ficha
//Ruta para vista Pacientes
Route::get('/dashboard/pacientes/{id}', 'FichaController@buscarPaciente')->name('buscar');

// Ruta para filtrar pacientes
Route::get('/dashboard/filtrarPaciente', 'FichaController@filtroPaciente')->name('filtrarPaciente');
//Ruta para vista 'Información de pacientes'
Route::get('/dashboard/information/{id}', 'FichaController@informationPaciente')->name('information');

//Ruta para vista 'Creación diagnóstico' de pacientes
Route::get('/dashboard/create/{id}', 'FichaController@crearDiagnostico')->name('create');

//Ruta para vista 'Egresar pacientes'
Route::get('/dashboard/egresarPaciente/{id}', 'FichaController@egresarPaciente')->name('egresarPaciente');

//Ruta para dar de alta a un paciente
Route::put('/dashboard/alta-Paciente/{id}', 'FichaController@altaPaciente')->name('alta-Paciente');

// Ruta para guardar diagnóstico en base de datos
Route::post('/dashboard/guardar_diagnostico/{id}', 'FichaController@guardarDiagnostico')->name('guardarDiagnosticoBD');

// Ruta para actualizar diagnostico en base de datos
Route::put('/dashboard/updateDiagnostico/{id}', 'FichaController@updateDiagnostico')->name('updateDiagnostico');

// Ruta para actualizar manual 1 en base de datos
Route::put('/dashboard/updateManual/{id}', 'FichaController@updateManual')->name('updateManual');

// Ruta para actualizar manual 2 en base de datos
Route::put('/dashboard/updateManual2/{id}', 'FichaController@updateManual2')->name('updateManual2');

// Ruta para actualizar manual 3 en base de datos
Route::put('/dashboard/updateManual3/{id}', 'FichaController@updateManual3')->name('updateManual3');

// Ruta para guardar manual en base de datos
Route::post('/dashboard/guardar_manual/{id}', 'FichaController@guardarManual')->name('guardarManualBD');

// Ruta para guardar comentarios en base de datos
Route::post('/dashboard/guardar_comentario/{id}', 'FichaController@guardarComentario')->name('guardarComentarioBD');

//Ruta para vista 'Ver diagnóstico' de pacientes
Route::get('/dashboard/show/{id}', 'FichaController@verDiagnostico')->name('show');

Route::get('/dashboard/nuevomanual/{id}', 'FichaController@informationManuales')->name('newmanual');

//Descargar PDF
Route::get('/dashboard/download-pdf/{id}','FichaController@downloadPdf')->name('downloadPdf');

//Descargar PDF
Route::get('/dashboard/download-Ficha/{id}','FichaController@downloadFicha')->name('descargarFicha');

//Ruta para vista 'Menú Sesiones' de pacientes
Route::get('/dashboard/sesiones/{id}', 'FichaController@verSesiones')->name('sesiones');

// Ruta para guardar sesión en base de datos
Route::post('/dashboard/guardar_sesion/{id}', 'FichaController@guardarSesion')->name('guardarSesionBD');

// Ruta para filtrar por numero de sesion
Route::get('/dashboard/busqueda{id}', 'FichaController@filtrarnumero')->name('filtrarnumero');
// Término Rutas ficha



Route::get('/datosModi', 'ServicioController@datosModi');
Route::put('/servicio/editar', 'ServicioController@update')->name('up');


//Rutas pasarela de pago (WebpayNormal)
//Route::post('pasareladepago/webpay/pagar','WebPayController@pagar')->name('pasareladepago.webpay.pagar');
Route::post('pasareladepago/webpay/response', 'WebPayController@response')->name('pasareladepago.webpay.response');
Route::post('pasareladepago/webpay/finish', 'WebPayController@finish')->name('pasareladepago.webpay.finish');
Route::get('pasareladepago/webpay/vista', 'WebPayController@vista')->name('pasareladepago.webpay.vista');
Route::get('pasareladepago/webpay/pagodetalle/{id}', 'WebPayController@pagodetalle')->name('pasareladepago.webpay.pagodetalle');
Route::get('pasareladepago/webpay/visualizaciondetalle/{id}', 'WebPayController@visualizacionDetalle')->name('pasareladepago.webpay.visualizaciondetalle');

Route::get('pasareladepago/webpay/correo', 'WebPayController@correo')->name('pasareladepago.webpay.correo');
Route::post('pasareladepago/webpay/correoopcional', 'WebPayController@correoOpcional')->name('pasareladepago.webpay.correoopcional');
Route::get('pasareladepago/webpay/ordencompra/{id}', 'WebPayController@ordenDeCompra')->name('pasareladepago.webpay.ordencompra');

app/Servicio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Servicio extends Model
{
    protected $table = "servicio";
    protected $primary_key = "id";
    public $timestamps = false;

    protected $fillable = [
        'id',
        'nombre', 
        'descripcion',
        'duracion',
        'user_id',
    ];
    
    public function modalidad(){
        return $this->hasMany('App\ModalidadServicio');
    }

    public function precio(){
        return $this->hasMany('App\PrecioServicio');
    }

    public function isapre(){
        return $this->hasMany('App\IsapreServicio');
    }
    public function cita(){
        return $this->hasMany('App\Cita');
    }
}

resources/views/servicios/agregarServicio.blade.php
<script src="{{asset('assets/js/steperServicio.js')}}"></script>
<div class="modal fade" id="create">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="mb-3">Agregar un servicio</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span>x</span>
                </button>
            </div>
            <div class="model-body " id="modal_body">
            <!-- Formulario para agregar servicios -->
                <div class="card-body">
                    <form id="formAddS" >
                        @csrf
                        @include('servicios.pasos')
                        <div id="msgError"></div>
                        @include('servicios.formPasos')
                        <input type="hidden" id="user_id" name="user_id" value="{{auth()->id()}}"> 
                    </form>
                    <div class="mt-5 pb-5">
                        <div class="col-lg-4 col-6 float-left">
                                <button type="button" class="btn btn-block indigo-border white indigo-text text-4" id="prevBtn" onclick="nextPrev(-1)"><i class="fas fa-arrow-left"></i> Atras</button>
                        </div>
                        <div class="col-lg-4 col-6 float-right" id="next">
                            <button type="button" class="btn btn-block indigo white-text text-4" id="nextBtn" onclick="nextPrev(1)">Siguiente <i class="fas fa-arrow-right"></i></button>
                        </div>
                        <div class="col-lg-4 col-6 float-right" >
                            <button type="submit" id="addS" style="display:none;" class="btn btn-block green white-text text-4">Finalizar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/servicios/dashboardServicios.blade.php
<!-- sección de scripts -->
    <!-- Scripts para mostrar/esconder div del formulario y botones de eliminar -->

    <script src="{{ asset('assets/js/servicios/hideShowDiv.js') }}"></script>

    <!-- Script para validar el formulario de los servicios -->

    <script src="{{ asset('assets/js/servicios/validarFormServices.js') }}"></script>

    <!-- Script para validar el formulario de los servicios al editar -->

    <script src="{{ asset('assets/js/servicios/validarFormEditar.js') }}"></script>

@extends('layouts.dashboard')
@section('contentSidebar')
    <div class="container-fluid" id="list-servicio"></div>
@endsection

<input type="hidden" id="idPerfil" value="{{auth()->id()}}">

<!-- Script para traer los servicios y mostrarlos en el div -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>

    $(document).ready(function(){
        listServicio();
    });

    var listServicio = function(){
        var idPerfil = document.getElementById('idPerfil').value;
        var dataString = "id="+idPerfil;
        $.ajax({
            type: 'get',
            url: '{{url('serviciosall')}}',
            data: dataString,
            success: function(data){
                $('#list-servicio').empty().html(data);
            }
        });
    }

</script>

resources/views/servicios/editarServicio.blade.php
<script src="{{asset('assets/js/steperServicioEditar.js')}}"></script>
<div class="modal fade" id="edit">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="mb-3">Editar un servicio</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span>x</span>
                </button>
            </div>
            <div class="model-body " id="modal_body">
            <!-- Formulario para agregar servicios -->
                <div class="card-body">
                    <form id="formEditS" >
                        @csrf
                        <div id="msgErrorEditar"></div>
                        @include('servicios.formPasosEditar')
                        <input type="hidden" id="user_id" name="user_id" value="{{auth()->id()}}"> 
                    </form>
                    <div class="mt-5 pb-5">
                        <div class="col-lg-4 col-6 float-left">
                                <button type="button" class="btn btn-block indigo-border white indigo-text text-4" id="prevBtnEd" onclick="nextPrevEd(-1)"><i class="fas fa-arrow-left"></i> Atras</button>
                        </div>
                        <div class="col-lg-4 col-6 float-right" id="nextEd">
                            <button type="button" class="btn btn-block indigo white-text text-4" id="nextBtnEd" onclick="nextPrevEd(1)">Siguiente <i class="fas fa-arrow-right"></i></button>
                        </div>
                        <div class="col-lg-4 col-6 float-right">
                            <button type="submit" id="editS" style="display:none;" class="btn btn-block green white-text text-4">Guardar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/servicios/pasos.blade.php
<div class="mb-4">
    <div class="row d-flex justify-content-center">
        <div class="col-3 d-flex justify-content-center">
            <span class="step rounded-circle d-flex justify-content-center far fa-file-alt align-self-center"></span>
        </div>
        <div class="col-1 d-flex justify-content-center p-0">
            <div class="line align-self-center"></div>
        </div>
        <div class="col-3 d-flex justify-content-center">
            <span class="step rounded-circle d-flex justify-content-center fas fa-search-location align-self-center"></span>
        </div>
        <div class="col-1 d-flex justify-content-center p-0">
            <div class="line align-self-center "></div>
        </div>
        <div class="col-3 d-flex justify-content-center">
            <span class="step rounded-circle d-flex justify-content-center fas fa-hand-holding-usd align-self-center"></span>
        </div>
    </div>
</div>

resources/views/servicios/pasosEditar.blade.php
<div class="mb-4">
    <div class="row d-flex justify-content-center">
        <div class="col-3 d-flex justify-content-center">
            <span class="stepEd rounded-circle d-flex justify-content-center far fa-file-alt align-self-center"></span>
        </div>
        <div class="col-1 d-flex justify-content-center p-0">
            <div class="line align-self-center"></div>
        </div>
        <div class="col-3 d-flex justify-content-center">
            <span class="stepEd rounded-circle d-flex justify-content-center fas fa-search-location align-self-center"></span>
        </div>
        <div class="col-1 d-flex justify-content-center p-0">
            <div class="line align-self-center "></div>
        </div>
        <div class="col-3 d-flex justify-content-center">
            <span class="stepEd rounded-circle d-flex justify-content-center fas fa-hand-holding-usd align-self-center"></span>
        </div>
    </div>
</div>

resources/views/servicios/serviciosall.blade.php
<div class="row">
    <div class="card" style="width: 100%;">
        <div class="card-body">
            <h4 class="text-1 darkblue-text mb-4"><b> Servicios </b> 
                <button class="btn btn-sm btn-right indigo white-text text-4 " data-toggle="modal" data-target="#create">
                    <i class="far fa-plus-square fa-fw"></i> Agregar servicio
                </button>
            </h4>
            @if(count($servicios)>0)
                @foreach($servicios as $servicio)
                <label class="text-4"><b>{{$servicio->nombre}}</b></label>
                <label name="lblEditar" class="btnEditDelete btn-right">
                    <button class="btn btn-sm white-text lightblue text-5 borde" id="btnEd" data-toggle="modal" data-target="#edit" data-id="{{$servicio->id}}">
                        <i class="fas fa-pencil-alt"></i> Editar
                    </button>
                </label>
                <label name="lblEliminar" class="btnEditDelete btn-right" style="padding-right: 0.5%;">
                    <button class="btn btn-sm white-text red text-5 deleteProduct borde" data-id="{{$servicio->id}}" data-token="{{ csrf_token() }}" >
                        <i class="fas fa-trash-alt"></i> Eliminar
                    </button>
                </label>
                <br>
                <label class="text-5" style="text-align: justify;">{{$servicio->descripcion}}</label><br>
                <button class="accordion borde" id="detalles" data-id="{{$servicio->id}}" data-duracion="{{$servicio->duracion}}"><i class="fas fa-tasks"></i> Detalles</button>
                <div class="panel">
                    <label><i class="far fa-clock"></i> <i><b> Duración: </i></b><label id="duracionX{{$servicio->id}}"></label> </label><br>
                    <label><i class="far fa-check-circle"></i> <i><b> Disponibilidad:</i></b>   
                    <ul>
                        @if($servicio->modalidad[0]->presencial != null)
                            <li>
                                Presencial: <i class="fas fa-check indigo-text"></i>
                            </li>
                        @endif
                        @if($servicio->modalidad[0]->online != null)
                            <li>
                                Atención remota: <i class="fas fa-check indigo-text"></i>
                            </li>
                        @endif
                        @if($servicio->modalidad[0]->visita != null)
                            <li>
                                Visita domiciliaria: <i class="fas fa-check indigo-text"></i>
                            </li>
                        @endif
                    </ul>
                    </label>
                    <label style="width:100%;"><i class="fas fa-search-dollar"></i> <i><b>Precios según previsión:</i></b></label>
                    <ul>
                        @if($servicio->precio[0]->precioFonasa != null)
                            <li>
                                Fonasa: <label>${{$servicio->precio[0]->precioFonasa}}</label>
                            </li>
                        @endif
                        @if($servicio->precio[0]->precioIsapre != null)
                            <li>
                                Isapre: <label>${{$servicio->precio[0]->precioIsapre}}</label>
                            </li>
                        @endif
                        @if($servicio->precio[0]->precioParticular != null)
                            <li>
                                Particular: <label>${{$servicio->precio[0]->precioParticular}}</label>
                            </li>
                        @endif
                    </ul>
                    @if($servicio->precio[0]->precioIsapre != null)
                    <label><i class="fas fa-user-shield"></i> <i> <b>Isapres disponibles:</b> </i> </label>
                        <ul>
                            @if($servicio->isapre[0]->banmedica != null)
                                <li>Banmédica</li>
                            @endif
                            @if($servicio->isapre[0]->consalud != null)
                                <li>Consalud</li>
                            @endif
                            @if($servicio->isapre[0]->colmena != null)
                                <li>Colmena</li>
                            @endif
                            @if($servicio->isapre[0]->cruzblanca != null)
                                <li>CruzBlanca</li>
                            @endif
                            @if($servicio->isapre[0]->masvida != null)
                                <li>Nueva Masvida</li>
                            @endif
                            @if($servicio->isapre[0]->vidatres != null)
                                <li>Vida Tres</li>
                            @endif
                        </ul>
                    @endif
                    </label>
                </div><hr>
                @endforeach
            @else
                <div class="alert alert-warning text-4">No hay servicios registrados</div>
            @endif  

        </div>
    </div>
    @include('servicios.agregarServicio')
    @include('servicios.editarServicio')
</div>

<!-- Script para agregar servicios con ajax -->

<script>

    $('#addS').click(function(event){

        event.preventDefault();

        var nombre = $("#nombre").val();
        var token = $("input[name=_token]").val();
        var form = $('#formAddS');
        var route = "{{route('servicio.store')}}";
        
        var ret = validar();
        
        //Ajax para insertar los servicios
        if (ret){
            $.ajax({
                type: "post",
                headers: {"X-CSRF-TOKEN":token},
                url: route,
                data: form.serialize(),
                dataType: "json",
                success: function (data) {
                    if(data.success == 'true' ){
                        //Ajax para mostrar los servicios en el div
                        listServicio();
                        //solucion al error del modal
                        $('.modal-backdrop').remove();
                    }
                }
            });
        }
    });
</script>

<!-- Script para eliminar servicios con ajax -->

<script>

$(".deleteProduct").click(function(){

    var id = $(this).data("id");
    var token = $(this).data("token");
    var route = "{{route('servicio.store')}}";

    //Ajax para eliminar servicios

    $.ajax(
    {
        url: route+"/"+id,
        type: 'DELETE',
        dataType: "JSON",
        data: {
            "id": id,
            "_method": 'DELETE',
            "_token": token,
        },
        success: function (data)
        {
            //Ajax para mostrar los servicios en el div
            listServicio();
            //botonesActivos();
        }
    });

});

</script>

<!-- Script para editar registros con ajax -->

<script>
    $('#editS').click(function(event){

        event.preventDefault();
        var token = $("input[name=_token]").val();
        var form = $('#formEditS');
        var route = "{{route('up')}}";

        var retEd = validarEd();
        
        //Ajax para insertar los servicios
        if (retEd){

            $.ajax({
                type: "PUT",
                headers: {"X-CSRF-TOKEN":token},
                url: route,
                data: form.serialize(),
                dataType: "json",
                success: function (data) {
                    /* if(data.success == 'true' ){
                        //Ajax para mostrar los servicios en el div
                        listServicio();
                        //solucion al error del modal
                        $('.modal-backdrop').remove();
                    } */
                }
            });
            listServicio();
            $('.modal-backdrop').remove();
        }
    });
</script>

<!-- Script para mostrar y ocultar los detalles -->

<script>

var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
    acc[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var panel = this.nextElementSibling;
        if (panel.style.maxHeight) {
        panel.style.maxHeight = null;
        } else {
        panel.style.maxHeight = panel.scrollHeight + "px";
        } 
    });
}

</script> 